---
- name: download spdk source code
  shell: git clone "{{ remote_url }}"
  args:
    chdir: "{{ user_dir }}"
  when: enabled_install == "spdk_alone"

- name: download spdk source code into ceph
  shell: git clone "{{ remote_url }}"
  args:
    chdir: "{{ ceph_dir }}"
  when: enabled_install == "ceph_spdk"

- name: Install the spdk dependency packages
  shell: sudo ./pkgdep.sh
  args:
    chdir: "{{ spdk_dir ]}"/scripts

- name: Download dpdk
  shell: sudo git submodule update --init
  args:
    chdir: "{{ spdk_dir }}"

### deploy spdk in Ubuntu, Debian, Centos, Fedora
- name: Install the dpdk
  shell: make install T=x86_64-native-linuxapp-gcc DESTDIR=./
  args:
    chdir: "{{ spdk_dir }}"/dpdk
  when:
    - (system_version == 'Ubuntu' or system_version == 'Debian') or (system_version == 'Centos' or system_version == 'Fedora')

- name: deploy the spdk
  shell: ./configure --with-dpdk=./dpdk/x86_64-native-linuxapp-gcc && make
  args:
    chdir: "{{ spdk_dir }}"
  when:
    - (system_version == 'Ubuntu' or system_version == 'Debian') or (system_version == 'Centos' or system_version == 'Fedora')


  ### deploy spdk in FreeBSD
- name: Install the dpdk
  shell: gmake install T=x86_64-native-linuxapp-gcc DESTDIR=./
  args:
    chdir: "{{ spdk_dir }}"/dpdk
  when:
    - system_version == 'Free'

- name: deploy the spdk
  shell: ./configure --with-dpdk=./dpdk/x86_64-native-linuxapp-gcc && gmake
  args:
    chdir: "{{ spdk_dir }}"
  when:
    - system_version == 'Free'